name: Publicar Diario IA

on:
  schedule:
    - cron: '0 8,20 * * *' # Se ejecuta a las 8:00 y a las 20:00 cada día
  workflow_dispatch: # Permite ejecutarlo manualmente con un botón

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Generar noticias
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python generador_noticias.py

      - name: Publicar cambios
        run: |
          git config --global user.name 'Editor IA'
          git config --global user.email 'bot@noreply.github.com'
          git add index.html
          git commit -m "Edición actualizada por IA" || exit 0
          git push